// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateItem(arg1) {
  return window['go']['main']['App']['CreateItem'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function GetItemByID(arg1) {
  return window['go']['main']['App']['GetItemByID'](arg1);
}

export function GetItems() {
  return window['go']['main']['App']['GetItems']();
}

export function UpdateItem(arg1) {
  return window['go']['main']['App']['UpdateItem'](arg1);
}
