// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateItem(arg1:string):Promise<string>;

export function DeleteItem(arg1:string):Promise<string>;

export function GetItemByID(arg1:number):Promise<main.Item>;

export function GetItems():Promise<string>;

export function UpdateItem(arg1:string):Promise<string>;
